# Generated by Django 3.0.2 on 2020-01-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200124_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
